#
# Grafana + Loki + Tempo + Prometheus
#
version: '3.8'
services:

  grafana:
    image: grafana/grafana-oss
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    env_file:
      - ./grafana/config.monitoring
    networks:
      - gfnet

  loki:
    image: grafana/loki
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - gfnet

  tempo:
    image: grafana/tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/tmp/tempo
    ports:
      - 9411:9411
      - 3200:3200
    networks:
      - gfnet

networks:
  gfnet:
